name: CI - SQL Lint

# Quand lancer le workflow
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'sql/**'                       # ne s'exécute que si des fichiers SQL ont changé
  push:
    branches:
      - main
    paths:
      - 'sql/**'
  workflow_dispatch:                   # lancement manuel depuis l'interface Actions

jobs:
  lint:
    name: Lint SQL (sqlfluff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Run sqlfluff lint
        run: |
          # vérifie la syntaxe et le style SQL dans le dossier sql/
          sqlfluff lint sql/ --dialect mysql
